import { Square } from "shogi2-types";
import {lance,knight,silver_general,gold_general,king1,king2,rook,pawn,bishop} from "./piece";

const boards:Square[][][]=[[
  [
    {piece:{id:crypto.randomUUID(),type:lance,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:knight,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:silver_general,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:gold_general,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:king1,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:gold_general,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:silver_general,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:knight,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:lance,owner:"player2"}}
  ],
  [
    {piece:null},
    {piece:{id:crypto.randomUUID(),type:rook,owner:"player2"}},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:{id:crypto.randomUUID(),type:bishop,owner:"player2"}},
    {piece:null}
  ],
  [
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player2"}}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:pawn,owner:"player1"}}
  ],
  [
    {piece:null},
    {piece:{id:crypto.randomUUID(),type:bishop,owner:"player1"}},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:{id:crypto.randomUUID(),type:rook,owner:"player1"}},
    {piece:null}
  ],
  [
    {piece:{id:crypto.randomUUID(),type:lance,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:knight,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:silver_general,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:gold_general,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:king2,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:gold_general,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:silver_general,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:knight,owner:"player1"}},
    {piece:{id:crypto.randomUUID(),type:lance,owner:"player1"}}
  ],
]];

export {boards};
