import {board} from "../types/global";
import {lance,knight,silver_general,gold_general,king1,king2,rook,pawn,bishop} from "./piece";

const boards:board[]=[[
  [
    {piece:{type:lance,player:"player2"}},
    {piece:{type:knight,player:"player2"}},
    {piece:{type:silver_general,player:"player2"}},
    {piece:{type:gold_general,player:"player2"}},
    {piece:{type:king1,player:"player2"}},
    {piece:{type:gold_general,player:"player2"}},
    {piece:{type:silver_general,player:"player2"}},
    {piece:{type:knight,player:"player2"}},
    {piece:{type:lance,player:"player2"}}
  ],
  [
    {piece:null},
    {piece:{type:rook,player:"player2"}},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:{type:bishop,player:"player2"}},
    {piece:null}
  ],
  [
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}},
    {piece:{type:pawn,player:"player2"}}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null}
  ],
  [
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}},
    {piece:{type:pawn,player:"player1"}}
  ],
  [
    {piece:null},
    {piece:{type:bishop,player:"player1"}},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:null},
    {piece:{type:rook,player:"player1"}},
    {piece:null}
  ],
  [
    {piece:{type:lance,player:"player1"}},
    {piece:{type:knight,player:"player1"}},
    {piece:{type:silver_general,player:"player1"}},
    {piece:{type:gold_general,player:"player1"}},
    {piece:{type:king2,player:"player1"}},
    {piece:{type:gold_general,player:"player1"}},
    {piece:{type:silver_general,player:"player1"}},
    {piece:{type:knight,player:"player1"}},
    {piece:{type:lance,player:"player1"}}
  ],
]];

export {boards};
