import { PieceType, Player } from "shogi2-types";
import { bishop, gold, king1, king2, knight, lance, pawn, rook, silver } from "./pieces";

export const pieces:{x:number,y:number,player:Player,type:PieceType}[]=[
  {x:0,y:0,player:"player2",type:lance},
  {x:1,y:0,player:"player2",type:knight},
  {x:2,y:0,player:"player2",type:silver},
  {x:3,y:0,player:"player2",type:gold},
  {x:4,y:0,player:"player2",type:king2},
  {x:5,y:0,player:"player2",type:gold},
  {x:6,y:0,player:"player2",type:silver},
  {x:7,y:0,player:"player2",type:knight},
  {x:8,y:0,player:"player2",type:lance},
  {x:0,y:8,player:"player1",type:lance},
  {x:1,y:8,player:"player1",type:knight},
  {x:2,y:8,player:"player1",type:silver},
  {x:3,y:8,player:"player1",type:gold},
  {x:4,y:8,player:"player1",type:king1},
  {x:5,y:8,player:"player1",type:gold},
  {x:6,y:8,player:"player1",type:silver},
  {x:7,y:8,player:"player1",type:knight},
  {x:8,y:8,player:"player1",type:lance},
  {x:0,y:2,player:"player2",type:pawn},
  {x:1,y:2,player:"player2",type:pawn},
  {x:2,y:2,player:"player2",type:pawn},
  {x:3,y:2,player:"player2",type:pawn},
  {x:4,y:2,player:"player2",type:pawn},
  {x:5,y:2,player:"player2",type:pawn},
  {x:6,y:2,player:"player2",type:pawn},
  {x:7,y:2,player:"player2",type:pawn},
  {x:8,y:2,player:"player2",type:pawn},
  {x:0,y:6,player:"player1",type:pawn},
  {x:1,y:6,player:"player1",type:pawn},
  {x:2,y:6,player:"player1",type:pawn},
  {x:3,y:6,player:"player1",type:pawn},
  {x:4,y:6,player:"player1",type:pawn},
  {x:5,y:6,player:"player1",type:pawn},
  {x:6,y:6,player:"player1",type:pawn},
  {x:7,y:6,player:"player1",type:pawn},
  {x:8,y:6,player:"player1",type:pawn},
  {x:1,y:1,player:"player2",type:rook},
  {x:7,y:7,player:"player1",type:rook},
  {x:1,y:7,player:"player1",type:bishop},
  {x:7,y:1,player:"player2",type:bishop},
];
