import {PieceType} from "shogi2-types";

export const diamond_is_unbreakable_pieces:PieceType[]=[
  {
    name:"群収",
    id:"harvest",
      movable:{
      absolute:[],
      relative:[[0,1]],
      func:[]
    },
    jumpable:false,
    promotion:undefined,
    promotion_callback:"",
    promotion_msg:[],
    king:false
  },
  {
    name:"悪社",
    id:"bad_campany",
      movable:{
      absolute:[],
      relative:[[0,1]],
      func:[]
    },
    jumpable:false,
    promotion:undefined,
    promotion_callback:"",
    promotion_msg:[],
    king:false
  },
  {
    name:"削界",
    id:"the_hand",
      movable:{
      absolute:[],
      relative:[
        ...[...Array(8)].map((_,i)=>[i+1,0]),
        ...[...Array(8)].map((_,i)=>[-i-1,0]),
        ...[...Array(8)].map((_,i)=>[0,i+1]),
        ...[...Array(8)].map((_,i)=>[0,-i-1]),
      ],
      func:[]
    },
    jumpable:true,
    promotion:undefined,
    promotion_callback:"",
    promotion_msg:[],
    king:false
  },
  {
    name:"爆魔",
    id:"killer_queen",
      movable:{
      absolute:[],
      relative:[],
      func:[]
    },
    jumpable:true,
    promotion_msg:[],
    promotion:undefined,
    promotion_callback:"",
    king:false
  },
  {
    name:"早人",
    id:"kawajiri_hayato",
      movable:{
      absolute:[],
      relative:[],
      func:[]
    },
    jumpable:true,
    promotion_msg:[],
    promotion:undefined,
    promotion_callback:"",
    king:false
  }
];
