import {PieceType} from "shogi2-types";

export const stone_ocean_pieces:PieceType[]=[
  {
    name:"緑坊",
    id:"green baby",
    src:"",
    movable:{
      absolute:[],
      relative:[[0,1]],
      func:""
    },
    jumpable:false,
    promotion:undefined,
    promotion_callback:"",
    promotion_msg:[],
    king:false
  },

  {
    name:"白蛇",
    id:"white snake",
    src:"",
    movable:{
      absolute:[],
      relative:[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]],
      func:""
    },
    jumpable:false,
    promotion:{
      name:"緑月",
      id:"c-moon",
      src:"",
      movable:{
        absolute:[],
        relative:[[2,0],[1,0],[-1,0],[-2,0],[0,2],[0,1],[0,-1],[0,-2],[2,2],[1,1],[-1,-1],[-2,-2],[2,-2],[1,-1],[-1,1],[-2,2]],
        func:""
      },
      jumpable:false,
      promotion:{
        name:"楽園",
        id:"made-in-heaven",
        src:"",
        movable:{
          absolute:[],
          relative:[...[...Array(8)].map((_,i)=>[0,i+1]),...[...Array(8)].map((_,i)=>[i+1,0]),...[...Array(8)].map((_,i)=>[0,-i-1]),...[...Array(8)].map((_,i)=>[-i-1,0]),...[...Array(8)].map((_,i)=>[i+1,i+1]),...[...Array(8)].map((_,i)=>[i+1,-i-1]),...[...Array(8)].map((_,i)=>[-i-1,i+1]),...[...Array(8)].map((_,i)=>[-i-1,-i-1])],
          func:""
        },
        jumpable:false,
        promotion:undefined,
        promotion_callback:"",
        promotion_msg:[],
        king:false
      },
      promotion_callback:"",
      promotion_msg:[],
      king:false
    },
    promotion_callback:"",
    promotion_msg:["\"彼\"の遺志を継ぐものですか？","はい","いいえ"],
    king:false
  },
  {
    name:"悪会社",
    id:"bad-campany",
    src:"",
    movable:{
      absolute:[],
      relative:[[0,1]],
      func:""
    },
    jumpable:false,
    promotion:undefined,
    promotion_callback:"",
    promotion_msg:[],
    king:false
  }
];
